$terminal = ghostty
$browser = chromium 
$fileManager = ghostty -e spf 
$files = ghostty -e spf 
$music = spotify 

bind = SUPER , Q, exec, ghostty 
bind = SUPER , S, exec, $music
bind = SUPER , E, exec, $files
bind = SUPER , B,  exec, $browser
bind = SUPER_SHIFT , B, exec, $browser --incognito
bind = SUPER , N, exec, $terminal -e nvim
bind = SUPER , T, exec, $terminal -e btop

bind = SUPER, W, killactive,
bind = SUPER, SPACE, exec, walker
bind = SUPER ALT, SPACE, exec, archen-menu-master
bind = SUPER, ESCAPE, exec, archen-system

bind = SUPER, J, togglesplit, # dwindle
bind = SUPER, P, pseudo, # dwindle
bind = SUPER, T, togglefloating,
bind = SUPER, F, fullscreen, 0
bind = SUPER CTRL, F, fullscreenstate, 0 2
bind = SUPER ALT, F, fullscreen, 1

bind = SUPER, LEFT, movefocus, l
bind = SUPER, RIGHT, movefocus, r
bind = SUPER, UP, movefocus, u
bind = SUPER, DOWN, movefocus, d

bind = SUPER, code:10, workspace, 1
bind = SUPER, code:11, workspace, 2
bind = SUPER, code:12, workspace, 3
bind = SUPER, code:13, workspace, 4
bind = SUPER, code:14, workspace, 5
bind = SUPER, code:15, workspace, 6
bind = SUPER, code:16, workspace, 7
bind = SUPER, code:17, workspace, 8
bind = SUPER, code:18, workspace, 9
bind = SUPER, code:19, workspace, 10

bind = SUPER SHIFT, code:10, movetoworkspace, 1
bind = SUPER SHIFT, code:11, movetoworkspace, 2
bind = SUPER SHIFT, code:12, movetoworkspace, 3
bind = SUPER SHIFT, code:13, movetoworkspace, 4
bind = SUPER SHIFT, code:14, movetoworkspace, 5
bind = SUPER SHIFT, code:15, movetoworkspace, 6
bind = SUPER SHIFT, code:16, movetoworkspace, 7
bind = SUPER SHIFT, code:17, movetoworkspace, 8
bind = SUPER SHIFT, code:18, movetoworkspace, 9
bind = SUPER SHIFT, code:19, movetoworkspace, 10

bind = SUPER, TAB, workspace, e+1
bind = SUPER SHIFT, TAB, workspace, e-1
bind = SUPER CTRL, TAB, workspace, previous

bind = SUPER SHIFT, LEFT, swapwindow, l
bind = SUPER SHIFT, RIGHT, swapwindow, r
bind = SUPER SHIFT, UP, swapwindow, u
bind = SUPER SHIFT, DOWN, swapwindow, d

bindmd = SUPER, mouse:272, Move window, movewindow
bindmd = SUPER, mouse:273, Resize window, resizewindow


bind = , PRINT, exec,     grim -g "$(slurp)" -t ppm - | satty --filename - --fullscreen --output-filename ~/Pictures/Screenshots/satty-$(date +'%Y%m%d-%H:%M:%S').jpg


bind = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume +5
bind = , XF86AudioLowerVolume, exec, swayosd-client --output-volume -5
bind = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle

bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+ && swayosd-client --brightness raise
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%- && swayosd-client --brightness lower

bind = SUPER, COMMA, exec, makoctl dismiss
bind = SUPER SHIFT, COMMA, exec, makoctl dismiss --all
bind = SUPER CTRL, COMMA, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"
