    [mgr]
    show_hidden = true
    [window]
    opacity = 0.9
        [opener]
            pdf = [
                        {run = 'okular "$@"', orphan = true, for = "unix" },
    ]
            image = [
                        {run = 'mirage "$@"', orphan = true, for = "unix" },
    ]
            play = [
                        {run = 'mpv "$@"', orphan = true, for = "unix" },

    ]
            edit = [  
                        { run = 'nvim "$@"', block = true, for = "unix" },
    ]

        [open]
    prepend_rules = [
    { name = "*.jpg", use = "image"},
    { name = "*.png", use = "image"},
    { name = "*.jpeg", use = "image"},
    { name = "*.pdf", use = "pdf"},
    { name = "*.txt", use = "edit"},
    ]
