"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](g_8)\
$os\
$username\
[](bg:red_glowing fg:g_8)\
$directory\
[](fg:red_glowing bg:red_ember)\
$git_branch\
$git_status\
[](fg:red_ember bg:red_flame)\
$c\
$rust\
[](fg:red_flame bg:red_glowing)\
$time\
[ ](fg:red_glowing)\
$line_break$character"""

palette = 'AirEnjoyer'



[palettes.AirEnjoyer]
red_flame = "#C53030"
g_8 = "#323232"
red_ember_glow = "#D87C4A"
red_ember = "#B14242"
red_glowing = "#DF6464"
text = "#B4B4B4"

[os]
disabled = false
style = "bg:g_8 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:g_8 fg:text"
style_root = "bg:g_8 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:g_8 bg:red_glowing"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:g_8 bg:red_ember"
format = '[[ $symbol $branch ](fg:g_8 bg:red_ember)]($style)'

[git_status]
style = "fg:g_8 bg:red_ember"
format = '[[($all_status$ahead_behind )](fg:g_8 bg:red_ember)]($style)'


[c]
symbol = " "
style = "fg:g_8 bg:red_flame"
format = '[[ $symbol( $version) ](fg:g_8 bg:red_flame)]($style)'

[rust]
symbol = ""
style = "fg:g_8 bg:red_ember"
format = '[[ $symbol( $version) ](fg:g_8 bg:red_ember)]($style)'



[time]
disabled = false
time_format = "%R"
style = "fg:g_8 bg:red_glowing"
format = '[[  $time ](fg:g_8 bg:red_glowing)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:red_glowing)'
error_symbol = '[](bold fg:red_glowing)'
vimcmd_symbol = '[](bold fg:red_glowing)'
vimcmd_replace_one_symbol = '[](bold fg:red_ember)'
vimcmd_replace_symbol = '[](bold fg:red_ember)'
vimcmd_visual_symbol = '[](bold fg:red_ember)'
