"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](grey)\
$os\
$username\
[](bg:purple fg:grey)\
$directory\
[](fg:purple bg:red)\
$git_branch\
$git_status\
[](fg:red bg:blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:blue bg:pink)\
$time\
[ ](fg:pink)\
$line_break$character"""

palette = 'AirEnjoyer'


[palettes.AirEnjoyer]
purple = "#BC9AE6"
grey = "#313244"
red = "#EBA0AC"
blue = "#89b4fa"
pink = "#FF7BFF"

text = "#BC9AE6"

[os]
disabled = false
style = "bg:grey fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:grey fg:text"
style_root = "bg:grey fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:grey bg:purple"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:blue"
format = '[[ $symbol $branch ](fg:grey bg:red)]($style)'

[git_status]
style = "bg:blue"
format = '[[($all_status$ahead_behind )](fg:grey bg:red)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:grey bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:grey bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:grey bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:grey bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:grey bg:blue)]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:grey bg:blue)]($style)'

[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:grey bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:grey bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:grey bg:blue)]($style)'


[time]
disabled = false
time_format = "%R"
style = "bg:pink"
format = '[[  $time ](fg:grey bg:pink)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:red)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:red)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:purple)'
